# Generated by Django 5.1.4 on 2024-12-25 08:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karaoke', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavoriteSong',
            new_name='FavoriteSongs',
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('recording', models.FileField(blank=True, null=True, upload_to='recordings/')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='karaoke.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
